web_acl_name = "deny-all_webacl"
web_acl_metics = "denyall"
waf_rule_name = "deny-all"
waf_rule_metrics = "denyallmetrics"
waf_rule_group_name = "deny-all_rule_group_name"
waf_rule_group_metrics = "deny_all-groupmetrics"
